### ISSUE TITLE
`target`: 'addon' with `isModuleUnification`: true looks to be not working

### ISSUE THREAD

**Issue by ppcano** [ember-cli/ember-cli-blueprint-test-helpers#185] opened 2018-11-16 20:47 UTC
emberjs/ember.js#17212 upgrades Ember to `ember-cli@3.5.0` and fix the blueprint tests. 

I had to skip all the `in-addon - module unification` tests (they are marked with `TODO mu new addon`), because they are not working with (`ember-cli@3.5.0` and `ember-cli-blueprint-test-helpers@0.19.1`)

When testing, I have realized that an MU addon test works if it runs in isolation (no more tests running). 

I don't know exactly how to debug the blueprint-test-helpers, so any help or guidance would be appreciated.

At this moment, the issue is blocking the migration of  Ember to `ember-cli@3.5.0`.

cc @dcyriller

**Comment by dcyriller** [comment] 2018-11-21 19:08
@ppcano I can reproduce the issue you faced in a test.

I suspect it has more to do with how the addon blueprint works internally than to these blueprint-test-helpers. Indeed, they merely proxy the ember project creation to ember-cli.

**Comment by dcyriller** [comment] 2018-11-21 19:12
...still investigating...

**Comment by dcyriller** [comment] 2018-11-29 17:34
Ok @ppcano I have it. When running multiple tests in sequence with `emberNew` helper (both with ap and addon), `ignoredFiles` gets incremented and never reset because we're writting on the prototype on this line: https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js#L702

I'm preparing a PR to fix this.

**Comment by ppcano** [comment] 2018-11-30 03:57
👏 @dcyriller,  I will test the PR with emberjs/ember.js#17212

**Comment by dcyriller** [comment] 2018-11-30 17:17
Closing this issue then

**Closed by dcyriller** 2018-11-30 17:17 UTC
